export const perizinanData = {
  overviews: [
    {
      id: 1,
      name: "TOTAL PERIZINAN",
      count: 766,
      icon: "bi-folder-fill",
      color: "primary",
    },
    {
      id: 2,
      name: "IZIN SEDANG DI PROSES",
      count: 5,
      icon: "bi-hourglass-split",
      color: "warning",
    },
    {
      id: 3,
      name: "IZIN SELESAI DI PROSES",
      count: 291,
      icon: "bi-check-circle-fill",
      color: "success",
    },
    {
      id: 4,
      name: "IZIN DITOLAK",
      count: 185,
      icon: "bi-x-circle-fill",
      color: "danger",
    },
    {
      id: 4,
      name: "SAMPAI KE PEMOHON",
      count: 285,
      icon: "bi-send-fill",
      color: "info",
    },
  ],
  sedang_proses: [
    {
      nama_proses: "Verifikasi Pendaftaran",
      jumlah: 0,
    },
    {
      nama_proses: "TTD Izin",
      jumlah: 0,
    },
    {
      nama_proses: "Melengkapi Data Perizinan",
      jumlah: 0,
    },
    {
      nama_proses: "Verifikasi Data Perizinan",
      jumlah: 0,
    },
    {
      nama_proses: "Validasi Izin",
      jumlah: 0,
    },
    {
      nama_proses: "Pembayaran",
      jumlah: 0,
    },
    {
      nama_proses: "Cetak Izin",
      jumlah: 0,
    },
    {
      nama_proses: "fo_pbg",
      jumlah: 0,
    },
    {
      nama_proses: "Validasi Final",
      jumlah: 2,
    },
    {
      nama_proses: "verifikasi_bpn",
      jumlah: 0,
    },
    {
      nama_proses: "Verifikasi Data",
      jumlah: 0,
    },
    {
      nama_proses: "Validasi Perizinan",
      jumlah: 0,
    },
    {
      nama_proses: "verifikasi_pupr",
      jumlah: 2,
    },
    {
      nama_proses: "Penonaktifan",
      jumlah: 0,
    },
    {
      nama_proses: "Validasi Penonaktifan",
      jumlah: 0,
    },
    {
      nama_proses: "Persetujuan Penonaktifan",
      jumlah: 0,
    },
    {
      nama_proses: "Dinas Kesehatan",
      jumlah: 1,
    },
  ],
  selesai_proses: [
    {
      nama_proses: "Survey Kepuasan",
      jumlah: 6,
    },
    {
      nama_proses: "Penyerahan Izin",
      jumlah: 0,
    },
    {
      nama_proses: "",
      jumlah: 285,
    },
  ],
  ditolak: [
    {
      nama_proses: "Penolakan",
      jumlah: 185,
    },
  ],
  sampai_pemohon: [
    {
      nama_proses: "Sampai ke Pemohon",
      jumlah: 285,
    },
  ],
};

export const perizinanData2 = {
  overviews: [
    {
      id: 1,
      name: "TOTAL PENDAFTARAN",
      count: 481,
      icon: "bi-folder-fill",
      color: "primary",
    },
    {
      id: 2,
      name: "TOTAL PROSES",
      count: 5,
      icon: "bi-hourglass-split",
      color: "warning",
    },
    {
      id: 3,
      name: "TOTAL SELESAI",
      count: 291,
      icon: "bi-check-circle-fill",
      color: "success",
    },
    {
      id: 4,
      name: "TOTAL DITOLAK",
      count: 185,
      icon: "bi-x-circle-fill",
      color: "danger",
    },
  ],
  bar: [
    {
      jenis_izin: "Izin Menggarap Tanah Timbul",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Optikal",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Penangkapan Ikan",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Pendirian Satuan Pendidikan (Operasional Sekolah)",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Pengusahaan Angkutan",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Penyelenggaraan Reklame",
      jml_pendaftaran: 132,
      jml_proses: 0,
      jml_selesai: 101,
      jml_ditolak: 31,
    },
    {
      jenis_izin: "Izin Penyelenggaraan Tempat Pelelangan Ikan",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Izin Trayek",
      jml_pendaftaran: 13,
      jml_proses: 0,
      jml_selesai: 10,
      jml_ditolak: 3,
    },
    {
      jenis_izin: "Izin Tukang Gigi",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Penonaktifan  Izin",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin:
        "Persetujuan Kesesuaian Kegiatan Pemanfaatan Ruang (PKKPR) Non Berusaha",
      jml_pendaftaran: 2,
      jml_proses: 2,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin:
        "Persetujuan Registrasi Pangan Segar Asal Tumbuhan (PSAT) Produksi Dalam Usaha Kecil (PDUK)",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Ahli Teknologi Laboratorium Medik",
      jml_pendaftaran: 11,
      jml_proses: 2,
      jml_selesai: 4,
      jml_ditolak: 5,
    },
    {
      jenis_izin: "Surat Izin Kerja Optometris",
      jml_pendaftaran: 2,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 2,
    },
    {
      jenis_izin: "Surat Izin Kerja Perekam Medis",
      jml_pendaftaran: 3,
      jml_proses: 0,
      jml_selesai: 1,
      jml_ditolak: 2,
    },
    {
      jenis_izin: "Surat Izin Kerja Radiografer",
      jml_pendaftaran: 5,
      jml_proses: 0,
      jml_selesai: 3,
      jml_ditolak: 2,
    },
    {
      jenis_izin: "Surat Izin Kerja Refraksionis Optisien",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Kerja Tenaga Gizi",
      jml_pendaftaran: 4,
      jml_proses: 0,
      jml_selesai: 3,
      jml_ditolak: 1,
    },
    {
      jenis_izin: "Surat Izin Kerja Tenaga Sanitarian",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Memimpin Sekolah Swasta",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Praktik Apoteker",
      jml_pendaftaran: 17,
      jml_proses: 0,
      jml_selesai: 10,
      jml_ditolak: 7,
    },
    {
      jenis_izin: "Surat Izin Praktik Bidan",
      jml_pendaftaran: 90,
      jml_proses: 0,
      jml_selesai: 36,
      jml_ditolak: 54,
    },
    {
      jenis_izin: "Surat Izin Praktik Dokter",
      jml_pendaftaran: 36,
      jml_proses: 1,
      jml_selesai: 19,
      jml_ditolak: 16,
    },
    {
      jenis_izin: "Surat Izin Praktik Dokter Hewan",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Praktik Elektromedis",
      jml_pendaftaran: 5,
      jml_proses: 0,
      jml_selesai: 1,
      jml_ditolak: 4,
    },
    {
      jenis_izin: "Surat Izin Praktik Fisiotrapis",
      jml_pendaftaran: 1,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 1,
    },
    {
      jenis_izin: "Surat Izin Praktik Penata Anestesi",
      jml_pendaftaran: 4,
      jml_proses: 0,
      jml_selesai: 3,
      jml_ditolak: 1,
    },
    {
      jenis_izin: "Surat Izin Praktik Perawat",
      jml_pendaftaran: 115,
      jml_proses: 0,
      jml_selesai: 80,
      jml_ditolak: 35,
    },
    {
      jenis_izin: "Surat Izin Praktik Psikolog Klinis",
      jml_pendaftaran: 5,
      jml_proses: 0,
      jml_selesai: 2,
      jml_ditolak: 3,
    },
    {
      jenis_izin: "Surat Izin Praktik Teknisi Kardiovaskuler",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Praktik Teknisi Pelayanan Darah",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Izin Praktik Tenaga Teknis Kefarmasian",
      jml_pendaftaran: 30,
      jml_proses: 0,
      jml_selesai: 16,
      jml_ditolak: 14,
    },
    {
      jenis_izin: "Surat Izin Praktik Terapis Gigi dan Mulut",
      jml_pendaftaran: 6,
      jml_proses: 0,
      jml_selesai: 2,
      jml_ditolak: 4,
    },
    {
      jenis_izin: "Surat Izin Praktik Terapis Wicara",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
    {
      jenis_izin: "Surat Terdaftar Penyehat Tradisional",
      jml_pendaftaran: 0,
      jml_proses: 0,
      jml_selesai: 0,
      jml_ditolak: 0,
    },
  ],
};
